$(function(){
	$("#KinSlideshow").KinSlideshow(
		{
                moveStyle:"right",
                titleBar:{titleBar_height:30,titleBar_bgColor:"#000",titleBar_alpha:0.5},
                titleFont:{TitleFont_size:12,TitleFont_color:"#FFFFFF",TitleFont_weight:"normal"},
                btn:{btn_bgColor:"#FFFFFF",btn_bgHoverColor:"#434343",btn_fontColor:"#000000",
                     btn_fontHoverColor:"#FFFFFF",btn_borderColor:"#fff",
                     btn_borderHoverColor:"#fff",btn_borderWidth:1}
        }
	);
})